### ISSUE TITLE
can't join multiplayer, missing a bunch of tags?

### ISSUE THREAD

**Issue by temyy** [glisco03/things#68] opened 2023-07-22 01:17 UTC
happens with owo lib 0.11.0 and things 0.3.1, both mods work just fine in a singleplayer world but as soon as i try joining a server that has those mods i get kicked with "connection lost %s". server log just says player disconnected but client log points to a bunch of missing tags
ive had a similar issue with betterend and its dependency bclib, but never figured out the cause for this
client log https://paste.atlauncher.com/view/fe63915c-50bc-4322-9c62-a645297b5e9a
server log attached as file
[latest.log](https://github.com/wisp-forest/things/files/12135360/latest.log)

**Comment by Noaaan** [comment] 2023-07-22 08:08
This is actually a bug with Quilt Standard Libraries, and should be fixed by this pull request: https://github.com/QuiltMC/quilt-standard-libraries/pull/326
I am not sure exactly what triggers the issue, but this is generally not something we can solve at this time.

**Closed as not planned** 2023-07-22 13:29 UTC
Labels: status: invalid, type: compatibility

**Comment by TropheusJ** [comment] 2023-07-22 16:12
Given that PR fixes a bug with a quilt-specific API, I don’t think it’s related.

**Comment by TropheusJ** [comment] 2023-07-22 16:24
Looked at the server log, definitely unrelated.

**Comment by gliscowo** [comment] 2023-07-22 16:25
Even in that case, I believe the chance of this being caused by Things to be *extremely* slim and would suspect some kind of Quilt problem either way
