### ISSUE TITLE
running shoes and bunny hopper's not working together.

### ISSUE THREAD

**Issue by johnuvm** [glisco03/things#101] opened 2024-08-31 05:21 UTC
I combined the running shoes and the bunny hoppers to the empty agglomeration and while it still kept the bunny hopper's ability of no fall damage, I no longer have the jump boost from it nor any of the running shoes abilities.

**Comment by Aesthir** [comment] 2024-09-02 22:17
This is a problem with anything placed into an agglomeration. Using an agglomeration bricks the trinkets in 1.21.

**Comment by Dragon-Seeker** [comment] 2024-09-03 23:57
Accessories builtin API for such has bugs that prevent some features of such to not work and issues within Accessories TCLayer would be the cause of Artifacts not working.

**Comment by Dragon-Seeker** [comment] 2024-09-03 23:58
An update will be come out coming up

**Comment by gliscowo** [comment] 2024-09-15 11:28
Seeing as this not a Things problem, I'll be closing this issue

Cheers

**Closed as not planned by gliscowo** 2024-09-15 11:28 UTC
