### ISSUE TITLE
retribution enchant Compat with basic shields [fabric]?

### ISSUE THREAD

**Issue by Skeithh** [glisco03/things#26] opened 2022-02-11 14:26 UTC
It looks like the Retribution Enchant isn't able to be put on shields from [basic shields [fabric]](https://www.curseforge.com/minecraft/mc-mods/basic-shields-fabric), it'd be lovely if that could be supported!

**Comment by gliscowo** [comment] 2022-02-11 18:52
How exactly have you run into this problem? Things already has compatibility measures in place and we just confirmed that they do in fact still work with the latest versions of all mods involved. Also, note that Retribution is a treasure enchantment and can thus never be applied at an enchantment table
Cheers

**Comment by Skeithh** [comment] 2022-02-13 17:30
I did find it as a treasure enchant, and all I was trying to do was apply it in an anvil like you'd do with any enchanted book. I'm not sure why it's not working in this case? Might be acting weird with some other mods so I'll try to look into it and see if I can pin down the culprit causing weirdness.

**Comment by gliscowo** [comment] 2022-02-28 00:58
Have you been able to track this down any further?

**Comment by gliscowo** [comment] 2022-04-23 21:10
Given that nobody else appears to have problems with this, and the fact it has been two months since the last activity on here I'll go ahead and close this

**Closed as completed by gliscowo** 2022-04-23 21:10 UTC
