### ISSUE TITLE
Jumpy on Socks stopped working suddenly

### ISSUE THREAD

**Issue by bbbower** [glisco03/things#40] opened 2022-06-26 18:09 UTC
Playing on Fabric Medieval Minecraft modpack V11 
things-0.2.17+1.18
For some reason the jump boost stopped working on socks. 
When held the NBT data for the item is 

{
 RepairCost: 1 as int,
 Enchantments: [
  {
   id: "yigd:soulbound",
   lvl: 1 as short
  }
 ],
 Speed: 2 as int,
 Jumpy: 1 as byte,
 JumpBoostDisabled: 1 as byte
}

I thought maybe a hotkey or something may have toggled them off as I was in a panic fighting a raid prior to noticing but there are no toggle keys anywhere that I can find.

**Comment by Noaaan** [comment] 2022-06-26 18:36
Toggling Jumpy on socks is done by sprinting while sneaking. It is detailed in the Things guide

**Comment by gliscowo** [comment] 2022-07-18 19:01
Given that this is almost certainly not a bug and simply a feature as detailed in the comment above, I will go ahead and close this as invalid
Cheers

**Closed as not planned by gliscowo** 2022-07-18 19:01 UTC
Labels: status: invalid
